CREATE DATABASE user_api;

\c user_api;


CREATE SEQUENCE users_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.users definition

-- Drop table

-- DROP TABLE users;

CREATE TABLE users (
	activo bool NOT NULL,
	actualizado_en timestamp(6) NULL,
	creado_en timestamp(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email varchar(255) NOT NULL,
	"password" varchar(120) NOT NULL,
	address varchar(255) NULL,
	date_birth date NULL,
	first_name varchar(255) NOT NULL,
	last_name varchar(255) NULL,
	mobile_phone varchar(255) NULL,
	"token" varchar(255) NULL,
	CONSTRAINT users_email_key UNIQUE (email),
	CONSTRAINT users_pkey PRIMARY KEY (id)
);


INSERT INTO users (
    activo, actualizado_en, creado_en, id, email, password, address,
    date_birth, first_name, last_name, mobile_phone, token
) VALUES 
(true, '2025-07-15 16:50:36.901', '2025-07-14 23:07:57.626', 14, 'a@a.com',
 '$2a$10$QjcaOJzHNJ7Ngr6e9kgB3ezMYuIQFOh2IcVl5.FYwVqjtgCu51Gly', 'Calle Falsa 123',
 '2000-01-01', 'Test', 'Uno', '3001234567',
 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhQGEuY29tIiwiaWF0IjoxNzUyNjE2MjM2LCJleHAiOjE3NTI3MDI2MzZ9.XtIe2i2AaARjjrGuWtYQKy8L7KTVb0KYoFno4pxhQls'),

(true, '2025-07-15 10:03:17.217', '2025-07-15 00:27:13.191', 18, 'caleb.villadiego@test.com',
 '$2a$10$5j1151K8/aEDHNonQAGc0uJBi0A0smSM/n./vDUNhnNVDUbOUiZ5q', 'Colombia',
 '2000-01-01', 'Caleb', 'Villadiego', '3001234567', NULL),

(true, '2025-07-15 10:21:47.895', '2025-07-14 23:08:45.463', 17, 'angulo@angulo.com',
 '$2a$10$uzr7jAWxc0xeyDJLAkbYPunqdax2LcFkgelbc/s/IX8RNgL7TKRna', 'angulandia',
 '2001-01-01', 'Angulo', 'Angulito', '3013156226', NULL),

(true, '2025-07-15 10:37:54.608', '2025-07-15 10:31:22.919', 19, 'angulo22nuevo@angulo.com',
 '$2a$10$FDFKf/4oqDv/ednp0h7qJOV7YR9str1.KIafaQYsmnxolVr/qEiGW', 'angulandia',
 '2001-01-01', 'Angulo', 'Angulito Angulon', '3013156226', NULL),

(true, '2025-07-15 15:22:25.808', '2025-07-15 15:22:25.808', 20, 'nuevo@usuario.com',
 '$2a$10$3MXQo7t89KnNIanBFhpO.eo0C/whh2Hu9OiY96KjBeqBiUkt.KjC2', 'Ciudad Test',
 '1995-05-10', 'Nuevo', 'Usuario', '3020000000', NULL);

GRANT ALL PRIVILEGES ON TABLE users TO postgres;

GRANT ALL ON SCHEMA public TO postgres;